config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'transactions#index'

  resources :transactions, only: :index
  resources :importations, only: %i[index create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/importation.rb
class Importation < ApplicationRecord
  enum importation_type: { transactions: 'transactions' }
  enum status: {
    waiting: 'waiting', in_progress: 'in_progress', completed: 'completed', error: 'error'
  }, _prefix: true

  validates :file, :importation_type, :status, presence: true

  mount_uploader :file, FileUploader
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :transactions

  validates :owner, :name, :balance, presence: true

  before_save :set_slug, if: :name_changed?

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :store
  belongs_to :transaction_type

  validates :store, :transaction_type, :datetime, :amount, :recipient_tax_id, presence: true

  after_create :update_store_balance

  private

  def update_store_balance
    if transaction_type.input?
      store.update(balance: store.balance + amount)
    else
      store.update(balance: store.balance - amount)
    end
  end
end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord
  enum procedure: { input: 0, output: 1 }

  validates :type_number, :description, :procedure, :signal, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/importations_controller.rb
class ImportationsController < ApplicationController

  def index
    @importation = Importation.new
    @importations = ImportationPresenter.wrap(Importation.order(created_at: :desc).last(10))
  end

  def create
    importation = Importation.new(importation_params)
    importation.status = :in_progress

    if importation.save
      ProcessFileImportationJob.perform_later(importation.id)
      flash[:info] = t('.flash.success')
    else
      flash[:warning] = importation.errors.full_messages.to_sentence
    end

    redirect_to importations_path
  end

  private

  def importation_params
    params.require(:importation).permit(:file, :importation_type)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :index, :set_stores

  def index
  end

  private

  def set_stores
    @stores = Store.all.collect { |s| [s.name, s.id] } || []
    @stores.prepend([t('.select_store.default'), 0])

    store = Store.find_by_id(params[:store_id] || session[:store_id])
    session[:store_id] = store.id if store.present?
    @current_store = StorePresenter.new(store)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-blu">
  <%= link_to 'Blu', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse right" id="navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(transactions_path) || current_page?(root_path) %>">
        <%= link_to t('navbar.transactions'), transactions_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(importations_path) %>">
        <%= link_to t('navbar.importations'), importations_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to t('navbar.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/importations/_form.html.erb
<%= form_for @importation do |f| %>
  <div class="row">
    <div class="col-sm-12 input-group mb-3">
      <div class="input-group-prepend">
        <%= f.label :importation_type, t('.select.label'), class: 'input-group-text' %>
      </div>
      <%= f.select :importation_type, ImportationPresenter.importation_types_for_enum, class: 'custom-select' %>
    </div>

    <div class="col-sm-12 col-md-6 input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="file_input">Upload</span>
      </div>
      <div class="custom-file">
        <%= f.file_field :file, class: 'custom-file-input', id: 'file_input', required: true, accept: '.txt' %>
        <label class="custom-file-label" for="file_input"><%= t('.file.label') %></label>
      </div>
    </div>

    <div class="col-sm-12 col-md-2">
      <%= submit_tag t('.submit'), class: 'btn btn-block btn-blu-primary' %>
    </div>
  </div>
<% end -%>

app/views/importations/index.html.erb
<% content_for :page_title, t('.page_title') %>

<div class="container pt-4">
  <div class="row title-container">
    <div class="col-12">
      <h1 class="m-0"><%= t('.title') %></h1>
    </div>
  </div>

  <hr class="mb-4"/>
  
  <div class="form-section mb-4">
    <%= render 'form' %>
  </div>
  
  <div class="row">
    <div class="col-12">
      <h4 class="mb-4"><%= t('.last_importations') %></h4>

      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Criado em</th>
            <th>Arquivo</th>
            <th>Tipo</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @importations.each do |importation| %>
            <tr>
              <td><%= importation.long_created_at %></td>
              <td><%= importation.file.identifier %></td>
              <td><%= importation.importation_type %></td>
              <td><%= importation.status %></td>
              <td><%= importation.meta %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <meta name="theme-color" content="#000000"/>

    <title><%= content_for?(:page_title) ? yield(:page_title) : t('.title') %></title>

    <link rel="icon" type="image/png" href="https://pagnet-production.s3.amazonaws.com/uploads/layout_setting/favicon/5/favicon.png" sizes="16x16" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= 'devise-body' if devise_controller? %>">
    <% unless devise_controller? %>
      <div class="navbar-content">
        <%= render 'navbar' %>
      </div>
    <% end %>

    <div class="flash-messages">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> text-center" role="alert"><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/index.html.erb
<% content_for :page_title, t('.page_title') %>

<div class="container pt-4">
  <div class="row title-container">
    <div class="col-sm-12 col-md-4 mb-2">
      <h1 class="m-0"><%= t('.title') %></h1>
    </div>
    <div class="col-sm-12 col-md-4 offset-md-4 mt-auto">
      <%= form_tag transactions_path, method: :get do %>
        <div class="input-group">
          <%= select :store_id, nil, @stores, { disabled: 0, selected: @current_store.try(:id) || '0' }, class: 'custom-select' %>
          <div class="input-group-append">
            <button class="btn btn-blu-primary" type="submit"><%= t('.select_store.submit') %></button>
          </div>
        </div>
      <% end -%>
    </div>  
  </div>

  <hr class="mb-4"/>
  
  <% if @current_store.present? %>
    <div class="row mb-3">
      <div class="col-sm-12 col-md-5 text-left mb-2">
        <h4><%= t('.owner', owner: @current_store.owner) %></h4>
      </div>
      <div class="col-sm-12 col-md-7 text-right">
        <h4><%= t('.store_balance', balance: @current_store.balance) %></h4>
      </div>
    </div>

    <div id="transactions_list" class="row transactions-list mb-4">
      <div class="col-sm-12 col-md-8 offset-md-2 px-0">
        <ul class="list-group list-group-flush">
          <% @current_store.transactions.each do |transaction| %>
            <li class="list-group-item">
              <div class="row">
                <div class="col-3 text-left">
                  <%= transaction.datetime %>
                </div>
                <div class="col-4 offset-1 text-center details">
                  <p class="d-block mb-0"><%= transaction.transaction_type.description %></p>
                  <a href="#transaction_item_<%= transaction.id %>" data-toggle="collapse">
                    <%= t('.details') %>
                  </a>
                </div>
                <div class="offset-1 col-3 text-right <%= transaction.procedure_class %>">
                  <%= transaction.transaction_type.signal %>
                  <%= transaction.amount %>
                </div>
              </div>
              <div class="collapse" id="transaction_item_<%= transaction.id %>" data-parent="#transactions_list">
                <p class="mb-1"><%= t('.transaction.card_number', card_number: transaction.card_number) %></h5>
                <p class="mb-0">
                  <%= t('.transaction.recipient_tax_id', recipient_tax_id: transaction.recipient_tax_id) %>    
                </p>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
    <h5 class="text-center text-muted">Selecione uma Loja</h5>
  <% end %>
</div>